name : Deploy to vercel prod

env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_PROD }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PROD }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  Deploy-to-prod:
    name: Deploy to Production (${{ github.event.inputs.tag }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information.
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_DEV_TODO_APP }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_DEV_TODO_APP }}

      - name: Deploy Project Artifacts to Vercel 
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_DEV_TODO_APP }}
        
