name: Deploy to Vercel Prod

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

concurrency:
  group: vercel-deploy-${{ github.event.inputs.tag }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Validate Tag Exists
        run: |
          if ! git ls-remote --tags origin | grep -q "refs/tags/${{ github.event.inputs.tag }}"; then
            echo "❌ Tag ${{ github.event.inputs.tag }} does not exist!"
            exit 1
          fi

      - name: Cache Node.js Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_PROD_TODO_APP }}

      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_PROD_TODO_APP }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vercel-build
          path: .vercel/output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: vercel-build
          path: .vercel/output

      - name: Deploy Project to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_PROD_TODO_APP }}

      - name: Send Notification on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{"text": "🚨 Deployment to Vercel **Failed!** Tag: ${{ github.event.inputs.tag }}"}' \
          YOUR_SLACK_WEBHOOK_URL
